"""Read SAP GUI control IDs off whatever screen is currently open.

This is how controls.yaml gets filled in. ZPRO is a custom transaction, so its
IDs exist only on your system - they cannot be supplied by anyone else.

    # open ZPRO's selection screen in SAP GUI, then:
    python tools/discover_controls.py

    # after opening an order, with Components View expanded:
    python tools/discover_controls.py --all

    # for a popup:
    python tools/discover_controls.py --window "wnd[1]"

    # write straight into a starter controls.yaml:
    python tools/discover_controls.py --yaml > discovered.yaml

For a table, note the Type in the output:
    GuiTableControl -> serial_column is the column INDEX ("7")
    GuiShell (ALV)  -> serial_column is the column NAME ("SERNR")
"""

from __future__ import annotations

import argparse
import sys

INPUTS = (
    "GuiTextField", "GuiCTextField", "GuiPasswordField", "GuiComboBox",
    "GuiCheckBox", "GuiRadioButton",
)
ACTIONS = ("GuiButton", "GuiToolbarControl", "GuiMenu")
TABLES = ("GuiTableControl", "GuiShell", "GuiGridView", "GuiTree")
INTERESTING = INPUTS + ACTIONS + TABLES


def describe(element) -> tuple[str, str, str, str]:
    kind = str(getattr(element, "Type", "?"))
    element_id = str(getattr(element, "Id", "?"))
    text = (getattr(element, "Text", "") or "").strip()
    tooltip = (getattr(element, "Tooltip", "") or "").strip()
    return kind, element_id.split("ses[0]/", 1)[-1], text, tooltip


def walk(element, depth: int, show_all: bool, found: list) -> None:
    kind, short_id, text, tooltip = describe(element)

    if show_all or kind in INTERESTING:
        label = f"  text={text!r}" if text else ""
        hint = f"  tooltip={tooltip!r}" if tooltip and tooltip != text else ""
        print(f"{'  ' * depth}{kind:<20} {short_id}{label}{hint}")
        found.append((kind, short_id, text or tooltip))

        if kind in TABLES:
            _describe_table(element, depth + 1)

    children = getattr(element, "Children", None)
    if children is None:
        return
    for index in range(children.Count):
        walk(children(index), depth + 1, show_all, found)


def _describe_table(table, depth: int) -> None:
    """Print a table's columns, which is what serial_column needs."""
    pad = "  " * depth
    rows = getattr(table, "RowCount", None) or getattr(table, "VisibleRowCount", None)
    print(f"{pad}-> rows: {rows}")

    columns = getattr(table, "Columns", None)
    if columns is not None:
        try:
            names = [columns(i).Name for i in range(columns.Count)]
            print(f"{pad}-> columns (use the NAME for an ALV grid): {names}")
            return
        except Exception:
            pass

    try:  # ALV grid exposes column order as a plain array
        print(f"{pad}-> column order: {list(table.ColumnOrder)}")
    except Exception:
        print(f"{pad}-> columns not enumerable; use the column INDEX")


def emit_yaml(found: list) -> None:
    """Print a controls.yaml skeleton with every candidate as a comment."""
    print("# Generated by discover_controls.py - move the right ids into place.")
    print("zpro:")
    for key in (
        "work_order_field", "order_display_field", "execute_button",
        "components_expand_button", "serial_table", "serial_column",
        "post_goods_issue_checkbox", "post_button", "confirm_button",
    ):
        print(f"  {key}: null")
    print("\n# Candidates seen on this screen:")
    for kind, element_id, label in found:
        suffix = f"   # {label}" if label else ""
        print(f"#   {kind:<20} {element_id}{suffix}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--window", default="wnd[0]",
                        help="window to dump (wnd[1] for a popup)")
    parser.add_argument("--all", action="store_true",
                        help="show every element, not just inputs/buttons/tables")
    parser.add_argument("--yaml", action="store_true",
                        help="emit a controls.yaml skeleton")
    args = parser.parse_args()

    try:
        import win32com.client
    except ImportError:
        print("pywin32 is not installed, or this is not Windows.", file=sys.stderr)
        return 1

    try:
        gui = win32com.client.GetObject("SAPGUI")
        session = gui.GetScriptingEngine.Children(0).Children(0)
    except Exception as exc:
        print(f"Could not attach to SAP GUI: {exc}", file=sys.stderr)
        print(
            "Is SAP GUI running? Is scripting enabled "
            "(Options > Accessibility & Scripting > Scripting)?",
            file=sys.stderr,
        )
        return 1

    info = session.Info
    print(f"System {info.SystemName} client {info.Client} "
          f"user {info.User} transaction {info.Transaction}")
    print("-" * 78)

    found: list = []
    try:
        walk(session.findById(args.window), 0, args.all, found)
    except Exception as exc:
        print(f"Could not read {args.window}: {exc}", file=sys.stderr)
        return 1

    if args.yaml:
        print()
        emit_yaml(found)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
